openapi: 3.0.1
info:
  title: 書籍管理システム API仕様
  description: 書籍管理システムのAPI仕様書です。
  version: v0.1
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Book
  description: 書籍情報
- name: Rental
  description: レンタル情報
- name: RentalUser
  description: レンタルユーザ情報
paths:
  /user/{userId}:
    put:
      tags:
      - RentalUser
      summary: レンタルユーザ情報更新API
      operationId: update
      parameters:
      - name: userId
        in: path
        description: 書籍ID
        required: true
        schema:
          type: string
        example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentalUserUpdateForm'
        required: true
      responses:
        "200":
          description: 成功
  /user:
    post:
      tags:
      - RentalUser
      summary: レンタルユーザ情報登録API
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentalUserRegisterForm'
        required: true
      responses:
        "200":
          description: 成功
  /rental:
    post:
      tags:
      - Rental
      summary: レンタル情報登録API
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentalRegisterForm'
        required: true
      responses:
        "200":
          description: 成功
  /book:
    get:
      tags:
      - Book
      summary: 書籍情報検索API
      operationId: search
      parameters:
      - name: id
        in: query
        description: 書籍ID
        required: false
        schema:
          type: string
        example: 1
      - name: name
        in: query
        description: 書籍名
        required: false
        schema:
          type: string
        example: ONE PIECE
      - name: author
        in: query
        description: 著者名
        required: false
        schema:
          type: string
        example: 尾田 栄一郎
      - name: page
        in: query
        description: Zero-based page index (0..N)
        required: false
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: size
        in: query
        description: The size of the page to be returned
        required: false
        schema:
          minimum: 1
          type: integer
          default: 20
      - name: sort
        in: query
        description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: 成功
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageBookSearchResponse'
    post:
      tags:
      - Book
      summary: 書籍情報登録API
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRegisterForm'
        required: true
      responses:
        "200":
          description: 成功
  /book/{bookId}:
    get:
      tags:
      - Book
      summary: 書籍情報詳細取得API
      operationId: detail
      parameters:
      - name: bookId
        in: path
        description: 書籍ID
        required: true
        schema:
          type: string
        example: 1
      responses:
        "200":
          description: 成功
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BookDetailResponse'
components:
  schemas:
    RentalUserUpdateForm:
      type: object
      properties:
        phone:
          type: string
        mail:
          type: string
    RentalUserRegisterForm:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        mail:
          type: string
    RentalRegisterForm:
      type: object
      properties:
        bookId:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        deadline:
          type: string
          format: date-time
    BookRegisterForm:
      type: object
      properties:
        name:
          type: string
        author:
          type: string
      description: 書籍登録フォーム
    BookSearchResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        author:
          type: string
      description: 書籍検索レスポンス
    PageBookSearchResponse:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/BookSearchResponse'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/SortObject'
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/PageableObject'
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/SortObject'
        paged:
          type: boolean
        unpaged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
    BookDetailRentalResponse:
      type: object
      properties:
        userId:
          type: string
        rentedAt:
          type: string
          format: date-time
      description: レンタル情報
    BookDetailResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        author:
          type: string
        rentals:
          type: array
          items:
            $ref: '#/components/schemas/BookDetailRentalResponse'
      description: 書籍詳細レスポンス
